### PR TITLE
Magic Items 4.0 release

### PR DESCRIPTION
**Pull request by PwQt**
The main part seems to be working fine, but still todo:
- [x] the spells/feats don't show for some reason on either default/tidy5e sheet

### CODE REVIEW

**Comment by PwQt** [comment]
It looks like the conversion api method is wrong atm.

**Comment by PwQt** [comment]
- [ ] No flags are present in the compendium packs

**Comment by PwQt** [comment]
Should be ready to release - testing now

**Comment by PwQt** [comment]
This should solve https://github.com/PwQt/magic-items-2/issues/89

**Comment by p4535992** [comment]
Just a note to update the module packs: 

- go to the directory `https://github.com/PwQt/magic-items-2/tree/master/src/packs/_source` and open the folder with visual studio
- just replace in all the jsons here  the string "magic-items-2" to  "magicitems" 
- `run-script build:db` packs the db with the new jsons
- `run-script build:json` unpack the db witht he new jsons
- commit and push

**Comment by PwQt** [comment]
@p4535992 Does that work also with VSCode or do I have to have full vs studio instance?

**Comment by p4535992** [comment]
> @p4535992 Does that work also with VSCode or do I have to have full vs studio instance?

Sorry i write "visual studio" i mean "visual code"
is just some npm commands, you can literally use the windows terminal or powershell and launch the same commands

**Pull request merged**
