### PR TITLE
Feature/dnd compat fixes

### PR DESCRIPTION
**Pull request by voodoofrog**
Here's the work I've done on getting the template working with the new sheet. I may have made some minor alterations here and there as well, but of course I will happily change anything at your request.

### CODE REVIEW

**Comment by voodoofrog** [comment]
Oh, and I also pulled in the latest from `master` too, as I'd assume that'd be happening at some point anyways.

**Comment by voodoofrog** [comment]
image
image

**Comment by voodoofrog** [comment]
Oh there's a bit of localization stuff still needing done too.

**Comment by PwQt** [comment]
Looks great, I'll use your stylings to adjust the `feats` template

**Comment by voodoofrog** [comment]
I can take a look at feats too if you'd like?

**Comment by p4535992** [comment]
Ty very much for the contribution !

**Comment by PwQt** [comment]
Already created the feats inside of the branch, will be verifying today/tomorrow whether everything's working.

**Pull request merged**
