### PR TITLE
Make the code more readable

### PR DESCRIPTION
**Pull request by p4535992**
We don't need to write all the code in a single file!!! vite takes care of embedding the result in a single javascript file.

I separated the various custom magic item implementations classes into separate javascript files to make it more readable to other developers following the standard patterns used by other developers in large projects...

### CODE REVIEW

**Comment by PwQt** [comment]
It's a good proposal, since I've clearly overtaken the previous owner's code. 

I'll see about reviewing this request up to end of the month.

**Comment by p4535992** [comment]
hei @PwQt   would you mind putting me as a github project contributor so I can manage PR and fix minor errors ? so I don't bother you with minor issues.

**Comment by PwQt** [comment]
Added you as one, wanted to do some work on it this week, but COVID has caught me and i've been *surviving*.

**Comment by p4535992** [comment]
@PwQt  no problem take care of yourself !! health first !!

**Comment by p4535992** [comment]
I think it is now ready for a release, anytime you want try to take a look at it.
I also updated the API documentation because honestly they are not super clear.

Due to lack of time I decided that I will open a committee on the league discord server to make an updated and improved version of this codcie for the 2.4.X version of the system... hopefully someone will be interested.

**Pull request merged**
