### PR TITLE
Bug fix : https://github.com/PwQt/magic-items-2/issues/33 again

### PR DESCRIPTION
**Pull request by p4535992**
Bug fix again https://github.com/PwQt/magic-items-2/issues/33
k this should be cover the string case too no ?

```
    // if is a number
    if (isRealNumber(value)) {
      return value;
    }
    // if is a string but with a numeric value
    else if (!isNaN(parseFloat(n)) && isFinite(n)) {
      return parseInt(value);
    }
    // if is something else
    else {
      return fallback;
    }
```

### CODE REVIEW

**Comment by PwQt** [comment]
It should be working, yes.

**Comment by p4535992** [comment]
no fuckkkkk is the wrong variable.... i'mtired...

**Comment by PwQt** [comment]
Lemme fix this then, go to bed 🤗

**Comment by p4535992** [comment]
just do it  a super fast pr  should be ok (i hope...)

**Pull request merged**
