### PR TITLE
Tidy Compatibility, Refactors, Bugfixes

### PR DESCRIPTION
**Pull request by kgar**
Related to #30 

## Item Sheet: Magic Item tab

- [x] Remove any references to Tidy Kgar from `magicitemtab.js`; this tab class will likely pertain only to the default and default(like) sheets.
- [x] Push show/hide enable/disable logic to the templates
- [x] Eliminate unnecessary magic item tab event handling (anything in the template with a `name` attribute saves itself on change)
- [x] Eliminate manual calls to `render` wherever able. Changes to MI tab data will trigger a re-render naturally.
- [x] Manually update the Item in certain cases. Things like delete buttons need to manually update the Item after adjusting MI data to remove the spell.
    - dropping on a new spell/feat/table
    - clicking to delete a spell/feat/table
- [x] Fix radio button issue
- [x] Proposed change: Leverage HTML structure of "Items with Spells" for the lists of Magic Item spells/feats/tables. It uses default styles naturally.
    - Here's what all would change: https://github.com/PwQt/magic-items-2/pull/46/commits/915c7550a7d9dde919697f5060ac77de659f95f1

## General/Misc.

- [x] Evaluate current practices like the magic item instance caching. From what I understand, the Magic Item class is an adapter to surface flag-based values in a useful way
    - I understand what's going on now. Basically, I can spin up a MagicItem anytime, as long as I have an Item5e document. At least in the Item tab, it is not really meant to be long-lived.
- [x] Resolve NaN's for the default sheets

## Tidy Compatibility

- [x] Register/configure Magic Item tab for item sheet
- [x] Add "Magic Item" wand icon to relevant inventory rows
- [x] Add Spellbook section for magic items
- [x] Add Features section for magic items
- [x] Handle MI2 events on Tidy sheets
    - This will require making some of the event handling code static (or simple functions with parameters) so that it can be shared.
- [x] Proposal: Use default-sheet-style HTML for the list tables, same as with the Magic Item Tab in the Item Sheet.

## Wrapping Up

- [ ] Default Sheets have the expected MI2 behavior
    - [ ] Item Sheet
    - [ ] Actor Sheet
- [ ] Original Tidy Sheets have the expected MI2 behavior
    - [ ] Item Sheet
    - [ ] Actor Sheet
- [ ] New Tidy Sheets have the expected MI2 behavior
    - [ ] Item Sheet
    - [ ] Actor Sheet

### CODE REVIEW

**Comment by kgar** [comment]
I got to a good stopping point for the day. If you are interested in pulling these changes in or testing out what I've done here, please feel free.

Tomorrow, I can continue to work on Tidy integration with the Actor sheet.

**Comment by kgar** [comment]
This will possibly fix #37 also

**Comment by PwQt** [comment]
Seems to be working and not breaking any compatibility, there are still few quirks (mostly visual) that I'll fix later.

Thanks for the gargantuan amount of work you did 😅 .

**Comment by kgar** [comment]
Thanks for letting me participate. If you ever want to chat about Foundry dev, I'm eager to discuss with other module devs, as I am still learning Foundry dev and techniques for building modules.

MI2 is very special to a lot of users. Some of my community members have been asking me about compatibility for a while now. I'm just glad that I could finally get New Tidy to a place where it could offer the appropriate tools for MI2 integration.

p4535992 has a commission for more work in MI2, and I'm interested in doing the work for that, however long it takes, as long as you're ok with that.

**Comment by PwQt** [comment]
Sure, as I've written previously, my history with this project is just having it working on Foundry v11, for me and my friends, so I did some minor fixes that took me way too long to figure it out. I also only have time to try and do some things on it during the weekends, since after work I don't really want to look at any code.

And I haven't really worked in any JavaScript-like languages, so that's another barrier of problems

And that's how we ended up here 😅 - any help is appreciated.

**Comment by kgar** [comment]
If you ever want to chat on discord, I'm there on the league server and on a few others, like the dedicated Tidy discord server (link on the repo readme). I'm glad to assist in gargantuan ways haha and will defer to your direction on things. I understand the module inner workings a lot better now that I've been in there a bit.

**Pull request merged**
